[2025-05-13T08:34:18.649+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-13T08:34:18.701+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sec_filing_scheduler.process_alny manual__2025-05-13T08:33:47.355026+00:00 [queued]>
[2025-05-13T08:34:18.716+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sec_filing_scheduler.process_alny manual__2025-05-13T08:33:47.355026+00:00 [queued]>
[2025-05-13T08:34:18.717+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-05-13T08:34:18.746+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_alny> on 2025-05-13 08:33:47.355026+00:00
[2025-05-13T08:34:18.791+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=556) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-13T08:34:18.814+0000] {standard_task_runner.py:72} INFO - Started process 568 to run task
[2025-05-13T08:34:18.862+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sec_filing_scheduler', 'process_alny', 'manual__2025-05-13T08:33:47.355026+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/orchestrate_clinical_pipeline.py', '--cfg-path', '/tmp/tmp3iq0v6sy']
[2025-05-13T08:34:18.874+0000] {standard_task_runner.py:105} INFO - Job 62: Subtask process_alny
[2025-05-13T08:34:19.667+0000] {task_command.py:467} INFO - Running <TaskInstance: sec_filing_scheduler.process_alny manual__2025-05-13T08:33:47.355026+00:00 [running]> on host 973c7a71adb3
[2025-05-13T08:34:19.927+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sec_filing_scheduler' AIRFLOW_CTX_TASK_ID='process_alny' AIRFLOW_CTX_EXECUTION_DATE='2025-05-13T08:33:47.355026+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-13T08:33:47.355026+00:00'
[2025-05-13T08:34:19.939+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-13T08:34:19.979+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-05-13T08:34:19.981+0000] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2025-05-13T08:34:21.043+0000] {logging_mixin.py:190} INFO - Found 141 8-K filings
[2025-05-13T08:34:21.044+0000] {logging_mixin.py:190} INFO - Found 13 10-K filings
[2025-05-13T08:34:21.044+0000] {logging_mixin.py:190} INFO - Found 37 10-Q filings
[2025-05-13T08:34:21.046+0000] {logging_mixin.py:190} INFO - Found 191 new filings.
[2025-05-13T08:34:21.046+0000] {logging_mixin.py:190} INFO - Processing 1 filings...
[2025-05-13T08:34:21.049+0000] {logging_mixin.py:190} INFO - Processing filing: 0001178670-25-000052
[2025-05-13T08:34:22.884+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-05-13T08:34:22.886+0000] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2025-05-13T08:34:23.458+0000] {logging_mixin.py:190} INFO - Finished 1/1: 0001178670-25-000052
[2025-05-13T08:34:23.470+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-05-13T08:34:23.471+0000] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2025-05-13T08:34:23.854+0000] {logging_mixin.py:190} INFO - Error processing filings: Unknown model publishers/google/models/gemini-2.5-flash-preview-04-17; {'gs://google-cloud-aiplatform/schema/predict/instance/chat_generation_1.0.0.yaml': <class 'vertexai.language_models.ChatModel'>}
[2025-05-13T08:34:23.857+0000] {logging_mixin.py:190} INFO - Deleted output_dir: sec_data/ALNY
[2025-05-13T08:34:23.858+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-13T08:34:23.886+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-13T08:34:23.887+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=sec_filing_scheduler, task_id=process_alny, run_id=manual__2025-05-13T08:33:47.355026+00:00, execution_date=20250513T083347, start_date=20250513T083418, end_date=20250513T083423
[2025-05-13T08:34:23.984+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-13T08:34:24.007+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-13T08:34:24.015+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
