[2025-05-13T08:11:30.116+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-13T08:11:30.136+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sec_filing_scheduler.process_wve manual__2025-05-13T08:10:57.970811+00:00 [queued]>
[2025-05-13T08:11:30.147+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sec_filing_scheduler.process_wve manual__2025-05-13T08:10:57.970811+00:00 [queued]>
[2025-05-13T08:11:30.148+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-05-13T08:11:30.172+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_wve> on 2025-05-13 08:10:57.970811+00:00
[2025-05-13T08:11:30.229+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=137) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-13T08:11:30.232+0000] {standard_task_runner.py:72} INFO - Started process 146 to run task
[2025-05-13T08:11:30.233+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sec_filing_scheduler', 'process_wve', 'manual__2025-05-13T08:10:57.970811+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/orchestrate_clinical_pipeline.py', '--cfg-path', '/tmp/tmpsxsy01j9']
[2025-05-13T08:11:30.235+0000] {standard_task_runner.py:105} INFO - Job 49: Subtask process_wve
[2025-05-13T08:11:30.301+0000] {task_command.py:467} INFO - Running <TaskInstance: sec_filing_scheduler.process_wve manual__2025-05-13T08:10:57.970811+00:00 [running]> on host 973c7a71adb3
[2025-05-13T08:11:30.457+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sec_filing_scheduler' AIRFLOW_CTX_TASK_ID='process_wve' AIRFLOW_CTX_EXECUTION_DATE='2025-05-13T08:10:57.970811+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-13T08:10:57.970811+00:00'
[2025-05-13T08:11:30.459+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-13T08:11:30.472+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-05-13T08:11:30.474+0000] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2025-05-13T08:11:31.402+0000] {logging_mixin.py:190} INFO - Found 135 8-K filings
[2025-05-13T08:11:31.409+0000] {logging_mixin.py:190} INFO - Found 10 10-K filings
[2025-05-13T08:11:31.417+0000] {logging_mixin.py:190} INFO - Found 29 10-Q filings
[2025-05-13T08:11:31.424+0000] {logging_mixin.py:190} INFO - No new filings to process.
[2025-05-13T08:11:31.427+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-13T08:11:31.547+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-13T08:11:31.549+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=sec_filing_scheduler, task_id=process_wve, run_id=manual__2025-05-13T08:10:57.970811+00:00, execution_date=20250513T081057, start_date=20250513T081130, end_date=20250513T081131
[2025-05-13T08:11:31.621+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-13T08:11:31.644+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-13T08:11:31.649+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
