[2025-05-13T21:09:35.586+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-13T21:09:35.608+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sec_filing_scheduler.process_alny manual__2025-05-13T21:09:23.263803+00:00 [queued]>
[2025-05-13T21:09:35.622+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sec_filing_scheduler.process_alny manual__2025-05-13T21:09:23.263803+00:00 [queued]>
[2025-05-13T21:09:35.623+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-05-13T21:09:35.642+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_alny> on 2025-05-13 21:09:23.263803+00:00
[2025-05-13T21:09:35.677+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=4157) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-13T21:09:35.680+0000] {standard_task_runner.py:72} INFO - Started process 4159 to run task
[2025-05-13T21:09:35.680+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sec_filing_scheduler', 'process_alny', 'manual__2025-05-13T21:09:23.263803+00:00', '--job-id', '110', '--raw', '--subdir', 'DAGS_FOLDER/orchestrate_clinical_pipeline.py', '--cfg-path', '/tmp/tmpgg2etr8q']
[2025-05-13T21:09:35.682+0000] {standard_task_runner.py:105} INFO - Job 110: Subtask process_alny
[2025-05-13T21:09:35.747+0000] {task_command.py:467} INFO - Running <TaskInstance: sec_filing_scheduler.process_alny manual__2025-05-13T21:09:23.263803+00:00 [running]> on host c1a7243cf3b7
[2025-05-13T21:09:35.919+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sec_filing_scheduler' AIRFLOW_CTX_TASK_ID='process_alny' AIRFLOW_CTX_EXECUTION_DATE='2025-05-13T21:09:23.263803+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-13T21:09:23.263803+00:00'
[2025-05-13T21:09:35.921+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-13T21:09:36.039+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-05-13T21:09:36.041+0000] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2025-05-13T21:09:37.160+0000] {logging_mixin.py:190} INFO - Found 142 8-K filings
[2025-05-13T21:09:37.161+0000] {logging_mixin.py:190} INFO - Found 13 10-K filings
[2025-05-13T21:09:37.161+0000] {logging_mixin.py:190} INFO - Found 37 10-Q filings
[2025-05-13T21:09:37.163+0000] {logging_mixin.py:190} INFO - No new filings to process.
[2025-05-13T21:09:37.163+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-13T21:09:37.179+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-13T21:09:37.180+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=sec_filing_scheduler, task_id=process_alny, run_id=manual__2025-05-13T21:09:23.263803+00:00, execution_date=20250513T210923, start_date=20250513T210935, end_date=20250513T210937
[2025-05-13T21:09:37.237+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-13T21:09:37.267+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-13T21:09:37.270+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
