[2025-05-13T08:19:50.733+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-13T08:19:50.759+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sec_filing_scheduler.process_wve manual__2025-05-13T08:19:15.858461+00:00 [queued]>
[2025-05-13T08:19:50.772+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sec_filing_scheduler.process_wve manual__2025-05-13T08:19:15.858461+00:00 [queued]>
[2025-05-13T08:19:50.773+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-05-13T08:19:50.803+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_wve> on 2025-05-13 08:19:15.858461+00:00
[2025-05-13T08:19:50.850+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=303) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-13T08:19:50.853+0000] {standard_task_runner.py:72} INFO - Started process 314 to run task
[2025-05-13T08:19:50.861+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sec_filing_scheduler', 'process_wve', 'manual__2025-05-13T08:19:15.858461+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/orchestrate_clinical_pipeline.py', '--cfg-path', '/tmp/tmp7sq1tznf']
[2025-05-13T08:19:50.864+0000] {standard_task_runner.py:105} INFO - Job 55: Subtask process_wve
[2025-05-13T08:19:50.950+0000] {task_command.py:467} INFO - Running <TaskInstance: sec_filing_scheduler.process_wve manual__2025-05-13T08:19:15.858461+00:00 [running]> on host 973c7a71adb3
[2025-05-13T08:19:51.123+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sec_filing_scheduler' AIRFLOW_CTX_TASK_ID='process_wve' AIRFLOW_CTX_EXECUTION_DATE='2025-05-13T08:19:15.858461+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-13T08:19:15.858461+00:00'
[2025-05-13T08:19:51.125+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-13T08:19:51.148+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-05-13T08:19:51.151+0000] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2025-05-13T08:19:52.456+0000] {logging_mixin.py:190} INFO - Found 135 8-K filings
[2025-05-13T08:19:52.459+0000] {logging_mixin.py:190} INFO - Found 10 10-K filings
[2025-05-13T08:19:52.461+0000] {logging_mixin.py:190} INFO - Found 29 10-Q filings
[2025-05-13T08:19:52.464+0000] {logging_mixin.py:190} INFO - No new filings to process.
[2025-05-13T08:19:52.466+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-13T08:19:52.494+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-13T08:19:52.496+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=sec_filing_scheduler, task_id=process_wve, run_id=manual__2025-05-13T08:19:15.858461+00:00, execution_date=20250513T081915, start_date=20250513T081950, end_date=20250513T081952
[2025-05-13T08:19:52.579+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-13T08:19:52.613+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-13T08:19:52.621+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
