[2025-05-13T20:02:35.875+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-13T20:02:35.916+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sec_filing_scheduler.process_wve manual__2025-05-13T20:01:47.115699+00:00 [queued]>
[2025-05-13T20:02:35.930+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sec_filing_scheduler.process_wve manual__2025-05-13T20:01:47.115699+00:00 [queued]>
[2025-05-13T20:02:35.931+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-05-13T20:02:35.956+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_wve> on 2025-05-13 20:01:47.115699+00:00
[2025-05-13T20:02:35.986+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3284) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-13T20:02:35.991+0000] {standard_task_runner.py:72} INFO - Started process 3285 to run task
[2025-05-13T20:02:35.990+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sec_filing_scheduler', 'process_wve', 'manual__2025-05-13T20:01:47.115699+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/orchestrate_clinical_pipeline.py', '--cfg-path', '/tmp/tmpiv1vnyd8']
[2025-05-13T20:02:35.992+0000] {standard_task_runner.py:105} INFO - Job 105: Subtask process_wve
[2025-05-13T20:02:36.123+0000] {task_command.py:467} INFO - Running <TaskInstance: sec_filing_scheduler.process_wve manual__2025-05-13T20:01:47.115699+00:00 [running]> on host c1a7243cf3b7
[2025-05-13T20:02:36.257+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sec_filing_scheduler' AIRFLOW_CTX_TASK_ID='process_wve' AIRFLOW_CTX_EXECUTION_DATE='2025-05-13T20:01:47.115699+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-13T20:01:47.115699+00:00'
[2025-05-13T20:02:36.259+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-13T20:02:36.343+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-05-13T20:02:36.345+0000] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2025-05-13T20:02:37.426+0000] {logging_mixin.py:190} INFO - Found 135 8-K filings
[2025-05-13T20:02:37.427+0000] {logging_mixin.py:190} INFO - Found 10 10-K filings
[2025-05-13T20:02:37.428+0000] {logging_mixin.py:190} INFO - Found 29 10-Q filings
[2025-05-13T20:02:37.430+0000] {logging_mixin.py:190} INFO - No new filings to process.
[2025-05-13T20:02:37.431+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-13T20:02:37.450+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-13T20:02:37.451+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=sec_filing_scheduler, task_id=process_wve, run_id=manual__2025-05-13T20:01:47.115699+00:00, execution_date=20250513T200147, start_date=20250513T200235, end_date=20250513T200237
[2025-05-13T20:02:37.538+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-13T20:02:37.569+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-13T20:02:37.573+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
